Реализовал базовую компоненту движения в коммите fbc4b65e7798c11b64ad2e466d1c308d1d7d851e
Dkoplik/Paint-it-Black pull request #26
Opened 2023-11-19 17:27 UTC by xzxolop

2023-11-19 18:39 UTC, xzxolop commented
Название получилось больно длинным из-за коммита

2023-11-19 19:30 UTC, Dkoplik commented
Не надо название коммита вставлять в pull-request, к тому же тут слияние нескольких коммитов идёт.

2023-11-19 19:46 UTC, Dkoplik requested changes

2023-11-19 19:46 UTC, Dkoplik commented on Paint-it-Black/basic_character_movement.gd
> +var is_falling: bool
Так как это приватные переменные и они не будут использоваться извне, то их названия лучше начинать с `_`. Неплохо бы добавить документирующие комментарии. А ещё переменные, по возможности, стоит инициализировать сразу.

2023-11-19 19:46 UTC, Dkoplik commented on Paint-it-Black/basic_character_movement.gd
> +var current_delta
Название переменной стоит начать с `_`, а ещё нет типизации и отсутсвует документирующий комментарий.

2023-11-19 19:46 UTC, Dkoplik commented on Paint-it-Black/basic_character_movement.gd
> +func _gravity_and_slide(delta) -> void:
Типизацию параметра `delta` лучше указать.

2023-11-19 19:46 UTC, Dkoplik commented on Paint-it-Black/basic_character_movement.gd
> +func _fall_speed(delta) -> float:
Аналогично, лучше указать типизацию параметра `delta`

2023-11-19 19:46 UTC, Dkoplik commented on Paint-it-Black/basic_character_movement.gd
> +	if speed<movement_data.max_fall_speed:
Опять беда с пробелами, такое тяжело читается. до и после `<` лучше добавить пробелы.

2023-11-19 19:46 UTC, Dkoplik commented on Paint-it-Black/basic_character_movement.gd
> +	character_body.velocity.x += velocity.x
Тут произошло небольшое недопонимание. Эта функция может толкнуть персонажа в любом направлении, не только по оси `x`. Короче, `.x` надо убрать.

2023-11-19 19:46 UTC, Dkoplik commented on Paint-it-Black/basic_character_movement.gd
> +		print("is idle")
Печать нужна только для тестов и не нужна в итоговом функционале.

2023-11-19 19:46 UTC, Dkoplik commented on Paint-it-Black/basic_character_movement.gd
> +	if (character_body.velocity.x == 0) and (character_body.velocity.y == 0) and not is_idle and not is_walking:
Вектор `velocity` можно сравнить на равентсво с `Vector2.ZERO`, а не проверять по каждой оси.

2023-11-19 19:46 UTC, Dkoplik commented on Paint-it-Black/basic_character_movement.gd
> +		print("is walking")
Опять убрать вывод. А ещё тут не испускается сам сигнал. На будущее проверку сигналов надо делать не в месте их отправки, а в отдельном скрипте, который принимает эти сигналы, иначе получится как тут: вывод о сигнале есть, а самого сигнала нет.

2023-11-19 19:46 UTC, Dkoplik commented on Paint-it-Black/basic_character_movement.gd
> +		print("is falling")
Убрать вывод.

2023-11-21 16:54 UTC, merged

2023-11-21 17:47 UTC, xzxolop commented
Исправил эти недочёты

2023-11-22 15:15 UTC, Dkoplik commented
> Исправил эти недочёты

1. Нет коммита с исправлениями этих недочётов.
2. Не надо было самостоятельно сливать и закрывать PR без моего обзора.