Реализовал компоненту движения PalyerMovement
Dkoplik/Paint-it-Black pull request #36
Opened 2023-11-24 16:01 UTC by xzxolop

Персонаж, в отличии от базовой компоненты, может прыгать, как от пола, так и от стен и скользить по стенам

2023-11-24 16:02 UTC, xzxolop commented
Мне не нравиться логика проверки сигналов, слишком много лишних переменных и функций получается. Вот такие пироги.

2023-11-25 13:07 UTC, Dkoplik requested changes
Есть совсем небольшие недочёты в реализации компоненты, но не понятно, зачем сюда прикреплять контроллер персонажа и почему была изменена сцена со скелетом игрока.

2023-11-25 13:07 UTC, Dkoplik commented on Paint-it-Black/player_movement.gd
> +	assert(movement_data != null and character_body != null)
Лучше эти условия разделить на разные assert'ы. Так будет более явно, какое условие не выполнилось, иначе в таком случае при ошибке надо будет ещё понять, какая именно переменная равняется null.

2023-11-25 13:07 UTC, Dkoplik commented on Paint-it-Black/player_movement.gd
> +		if wall_position.x>0: # стена слева
Беда с пробелами.

2023-11-25 13:07 UTC, Dkoplik commented on Paint-it-Black/player_movement.gd
> +func _check_jumping():
К `_check_sliding()` документирующий комментарий есть, а тут нет. Лучше добавить его по аналогии.

2023-11-25 13:07 UTC, Dkoplik commented on Paint-it-Black/test_anim.tscn
Почему сцена с скелетом игрока была изменена? Она не имеет никакого отношения к реализации компоненты движения и имять её здесь не надо было.

2023-11-25 14:57 UTC, xzxolop commented on Paint-it-Black/CharacterBody2D.gd
была тестовая сцена, файл не удалился

2023-11-25 14:58 UTC, xzxolop commented on Paint-it-Black/test_anim.tscn
я случайно((

2023-11-26 10:48 UTC, Dkoplik approved these changes

2023-11-26 10:48 UTC, Dkoplik commented on Paint-it-Black/player_movement.gd
> +	## проверка на то, что мы используем ресурсы игрока, а не что-то иное.
С двух решёток `##` начинаются документирующие комментарии, то есть какое-то описание функции или переменной, которое должно войти в документацию. С одной решётки `#` начинаются обычные комментарии по коду, в данном случае это просто комментарий к коду, поэтому нет смысла делать его документирующим.

2023-11-26 10:49 UTC, merged

2023-11-27 17:09 UTC, xzxolop reviewed
ура