Реализовал меню паузы
Dkoplik/Paint-it-Black pull request #44
Opened 2023-11-26 15:34 UTC by xzxolop

2023-11-26 15:35 UTC, xzxolop commented
Тут будут проблемы с тем, что кнопки в главном меню на английском, а в develop на русском

2023-11-26 17:32 UTC, Dkoplik requested changes
По какой-то причине, если из меню паузы выйти в главное меню, то главное меню не работает: обе кнопки просто не имеют никакого действия.

2023-11-26 17:32 UTC, Dkoplik commented on Paint-it-Black/palyer.gd
В чём смысл этой заготовки?

2023-11-26 17:49 UTC, Dkoplik commented
> По какой-то причине, если из меню паузы выйти в главное меню, то главное меню не работает: обе кнопки просто не имеют никакого действия.

Это исправляет сейчас не стоит, разберёся уже на практическом применении этих сцен.

2023-11-26 18:22 UTC, xzxolop commented
при переходе в главное меню из меню паузы оно не работает, т.к. мне было лень сделать по нормальному

2023-11-27 04:10 UTC, Dkoplik approved these changes

2023-11-27 04:10 UTC, merged